Log:
  Type: "Console" # Console、ile 
  Level: "Debug" # Debug、Info、Warn、Error

Etcd:
  Addrs: 
    - "127.0.0.1:2379"

RPCServer:
  ClusterName: "awesome_pine"
  ID: "" # 唯一ID
  Kind: connector # 服务器类型
  Host: 127.0.0.1 
  Port: 0
  Token: ksYNdrAo # 集群认证Token
  Labels:

Connector:
  Port: 3014