Log:
  Type: "Console" # Console File 
  Level: "Debug" # Debug Info Warn Error

Zookeeper:
  Host: 127.0.0.1
  Port: 2181

RPCServer:
  SystemName: "awesome_pine"
  ID: connector-0 # 唯一ID
  Kind: connector # 服务器类型
  Host: 127.0.0.1 
  Port: 3114 
  Token: ksYNdrAo # 集群认证Token

Connector:
  Port: 3014